#!/bin/bash

# Configure Supabase Authentication Settings
# This script configures the site URL and redirect URLs for proper authentication flow

echo "🔧 Configuring Supabase Authentication Settings..."

# Get the current project directory
PROJECT_DIR=$(pwd)

# Check if we're in the correct directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

# Configuration URLs
SITE_URL="https://waffle.cryptosi.org"
REDIRECT_URLS=(
    "https://waffle.cryptosi.org/auth/confirm"
    "https://waffle.cryptosi.org/auth/callback"
    "http://localhost:9002/auth/confirm"
    "http://localhost:9002/auth/callback"
    "http://localhost:3000/auth/confirm"
    "http://localhost:3000/auth/callback"
)

echo "📝 Configuration Details:"
echo "   Site URL: $SITE_URL"
echo "   Redirect URLs:"
for url in "${REDIRECT_URLS[@]}"; do
    echo "     - $url"
done

echo ""
echo "⚠️  IMPORTANT: You need to configure these settings in your Supabase Dashboard:"
echo ""
echo "1. Go to your Supabase Dashboard: https://supabase.com/dashboard/project/ogsvehiqkcdkirstguov"
echo "2. Navigate to: Authentication → Settings (or Configuration)"
echo "3. Update the following settings:"
echo ""
echo "   Site URL:"
echo "   $SITE_URL"
echo ""
echo "   Additional Redirect URLs (add each one):"
for url in "${REDIRECT_URLS[@]}"; do
    echo "   $url"
done

echo ""
echo "4. Save the changes"
echo ""
echo "🔍 Why this is needed:"
echo "   - Site URL: Default redirect after authentication"
echo "   - Redirect URLs: Whitelist of allowed callback URLs"
echo "   - This fixes email confirmation links redirecting to your app instead of Supabase Studio"
echo ""
echo "✅ After configuring these settings:"
echo "   - Email confirmation links will work properly"
echo "   - Users will be redirected to your app after authentication"
echo "   - OAuth flows will work correctly"
echo ""
echo "🚀 Next steps:"
echo "   1. Configure the settings in Supabase Dashboard"
echo "   2. Test email registration and confirmation"
echo "   3. Test wallet authentication"
echo ""

# Create a reminder file
cat > supabase-auth-config.md << EOF
# Supabase Authentication Configuration

## Required Settings in Supabase Dashboard

### Site URL
\`$SITE_URL\`

### Additional Redirect URLs
$(printf '%s\n' "${REDIRECT_URLS[@]}" | sed 's/^/- /')

## Steps to Configure

1. Go to [Supabase Dashboard](https://supabase.com/dashboard/project/ogsvehiqkcdkirstguov)
2. Navigate to: **Authentication → Settings**
3. Update **Site URL** to: \`$SITE_URL\`
4. Add each redirect URL to **Additional Redirect URLs**
5. Save changes

## What This Fixes

- ✅ Email confirmation links redirect to your app
- ✅ OAuth authentication flows work properly
- ✅ Password reset links work correctly
- ✅ Prevents CORS issues

## Testing

After configuration, test:
- [ ] Email registration and confirmation
- [ ] Password reset flow
- [ ] Wallet authentication
- [ ] OAuth providers (if configured)

---
*Generated by: configure-supabase-auth.sh*
*Date: $(date)*
EOF

echo "📄 Created reminder file: supabase-auth-config.md"
echo ""
echo "✨ Configuration guide complete!" 